apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-test-utils-aug29-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-test-utils-aug29-gitops
    spec:  
      serviceAccountName: test-utils-aug29-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/rh-ee-jdubrick/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=test-utils-aug29-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/test-utils-aug29-notebook -- git clone https://github.com/jdubrick-ai/test-utils-aug29
      restartPolicy: Never