---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-utils-aug29
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-utils-aug29 
  name: test-utils-aug29
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi